---
abstract: 'An almost back-compat fork of CGI::Application'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Snapp
provides:
  CGI::Snapp:
    file: lib/CGI/Snapp.pm
    version: 1.04
requires:
  CGI: 3.59
  CGI::PSGI: 0.15
  CGI::Simple: 1.113
  Capture::Tiny: 0.16
  Carp: 1.2
  Class::ISA: 0.36
  File::Spec: 0.86
  Hash::FieldHash: 0.1
  IO::Pipe: 1.13
  Log::Handler: 0.75
  Proc::Fork: 0.71
  Try::Tiny: 0.11
  parent: 0.225
  strict: 1.03
  vars: 1.01
  warnings: 1.03
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 1.04
